broodjes_homepage:
    pattern:  /
    defaults: { _controller: BroodjesBundle:Home:index }
broodjes_bestel:
    pattern:  /bestel
    defaults: { _controller: BroodjesBundle:Bestel:index }
broodjes_bestel_placeorder:
    pattern: /plaatsbestelling
    defaults: { _controller: BroodjesBundle:Bestel:placeorder }
broodjes_testbestel:
    pattern: /testbestel
    defaults: { _controller: BroodjesBundle:TestBestel:index }
