parameters:
#    broodjes.example.class: Broodjes\BroodjesBundle\Example

services:
#    broodjes.example:
#        class: %broodjes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
