parameters:
#    broodjes.example.class: Broodjes\BroodjesBundle\Example
    maxOrderHour: 16
    maxOrderMinutes: 30
    maxOrderNoticeMinutes: 15

services:
#    broodjes.example:
#        class: %broodjes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    broodjesUtils:
        class: Broodjes\BroodjesBundle\DependencyInjection\BroodjesUtils
        arguments: [%maxOrderHour%, %maxOrderMinutes%, %maxOrderNoticeMinutes%]