<?php

namespace Broodjes\BroodjesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BroodjesOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BroodjesOrderRepository extends EntityRepository
{
    public function findTodayByUser($user)
    {
        return $this->getEntityManager()
                ->createQuery(
                        'SELECT o'
                        . ' FROM BroodjesBundle:BroodjesOrder o'
                        . ' WHERE o.user = :currentuser'
                        . ' AND o.date = CURRENT_DATE()')
                ->setParameter('currentuser', $user)
                ->getResult();
    }
}
