Broodjes\BroodjesBundle\Entity\BreadType:
    type: entity
    table: breadtype
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
        price:
            type: float
    lifecycleCallbacks: {  }
