Broodjes\BroodjesBundle\Entity\BroodjesOrder:
    type: entity
    repositoryClass: Broodjes\BroodjesBundle\Entity\BroodjesOrderRepository
    table: broodjesorder
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
    oneToMany:
        #order<-->orderitem, One-To-Many Bidirectional
        orderitems:
            targetEntity: OrderItem
            mappedBy: broodjesorder
            cascade: [persist, merge]
    manyToOne:
        #order<-->user, Many-to-one Unidirectional
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
            cascade: [merge]
    lifecycleCallbacks: {  }
