Broodjes\BroodjesBundle\Entity\OrderItem:
    type: entity
    table: orderitem
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
    manyToOne:
        #orderitem<-->order, Many-to-one Bidirectional
        #orderitem holds a reference back to broodjesorder
        broodjesorder:
            targetEntity: BroodjesOrder
            inversedBy: orderitems
            joinColumn:
                name: broodjesorder_id
                referencedColumnName: id
        #orderitem<-->breadtype, Many-to-one Unidirectional
        #breadtype does not hold a reference back to orderitem
        breadtype:
            targetEntity: BreadType
            joinColumn:
                name: breadtype_id
                referencedColumnName: id
            cascade: [merge]
    manyToMany:
        #orderitem<-->topping, Many-to-many Unidirectional
        #toppings hold no reference back to orderitem
        toppings:
            targetEntity: Topping
            joinTable:
                name: orderitems_toppings
                joinColumns:
                    orderitem_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    topping_id:
                        referencedColumnName: id
            cascade: [merge]
    lifecycleCallbacks: {  }
