Broodjes\BroodjesBundle\Entity\OrderItem:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: integer
    manyToOne:
        broodjesorder:
            targetEntity: BroodjesOrder
            inversedBy: orderitems
            joinColumn:
                name: broodjesorder_id
                referencedColumnName: id
            cascade: [persist]
        breadtype:
            targetEntity: Breadtype
            joinColumn:
                name: breadtype_id
                referencedColumnName: id
            #cascade: [persist]
    manyToMany:
        toppings:
            targetEntity: Topping
            joinTable:
                name: orderitems_toppings
                joinColumns:
                    orderitem_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    topping_id:
                        referencedColumnName: id
            #cascade: [persist]
    lifecycleCallbacks: {  }
